[tool.poetry]
name = "kmkml"
version = "0.1.0"
description = ""
authors = ["I <I@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
